---
title: "Calendar plot in R using ggplot2"
author: "庄亮亮"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---
  
  
# 1. ggTimeSeries绘图
  
R中ggTimeSeries包[1]的`ggplot_calendar_heatmap()`函数可以绘制如图6-2-2(a)所示的日历图，但是不能设定日历图每个时间单元的边框格式。

使用`stat_calendar_heatmap()`函数和`ggplot2`包的`ggplot()`函数可以调整日历图每个时间单元的边框格式，具体代码如下所示。其关键是使用`as.integer(strftime())`日期型处理组合函数获取某天对应所在的年份、月份、周数等数据信息。
```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(data.table) # 数据格式依赖
library(ggTimeSeries)
library(RColorBrewer)
```


## 构造随机数据
```{r}
set.seed(2134)
dat <- data.table(
  date = seq(as.Date("2016-01-01"), as.Date("2019-12-31"), "days"),
  ValueCol = runif(1461)
)

dat[, ValueCol := ValueCol + (strftime(date, "%u") %in% c(6,7)*runif(1)*0.75)
][, ValueCol := ValueCol + (abs(as.numeric(strftime(date, "%m")) - 6.5))*runif(1)*0.75
][, ':='(Year = as.integer(strftime(date, "%Y")), # add new column
         month = as.integer(strftime(date, "%m")),
         week = as.integer(strftime(date, "%W")))] # 添加列

MonthLabels <- dat[, list(meanWkofYr = mean(week)), by = c("month")
][, month := month.abb[month]]
```


```{r}
ggplot(data = dat, aes(date = date, fill = ValueCol)) + 
  stat_calendar_heatmap() + 
  scale_fill_gradientn(colours = rev(brewer.pal(11, "Spectral"))) + 
  scale_y_continuous(name = NULL,
                     breaks = seq(7, 1, -1), 
                     labels = c("Mon", "Tue", "Wed", 
                                "Thu", "Fri", "Sat", "Sun")) + 
  scale_x_continuous(name = NULL, 
                     breaks = MonthLabels$meanWkofYr, 
                     labels = MonthLabels$month, 
                     expand = c(0,0)) + 
  facet_wrap(~Year, ncol = 1, strip.position = "right") + 
  theme(panel.background = element_blank(),
        panel.border = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(size = 13, face = "plain", color = "black"),
        axis.line = element_line(colour = "black", size = 0.25),
        axis.title = element_text(size = 10, face = "plain", color = "black"),
        axis.text = element_text(size = 10, face = "plain", color = "black"))

```


# 2.`geom_tile()`

使用R中`ggplot2`包的`geom_tile()`函数，借助`facet_wrap()`函数分面，就可以绘制如图6-2-2(b)所示的以月为单位的日历图，具体代码如下所示。

```{r}

label_mons <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", 
                "Aug", "Sep", "Oct", "Nov", "Dec")
label_wik <- c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

dat19 <- dat[Year == 2017, list(date, ValueCol, month, week)
][, ':='(weekday = as.integer(strftime(date, "%u")), # 周数
         yearmonth = strftime(date, "%m%Y"),       # 月数
         day = strftime(date, "%d"))              # 天数
][, ':='(monthf = factor(x = month, levels = as.character(1:12),
                         labels = label_mons, ordered = TRUE),
         weekdayf = factor(x = weekday, levels = 1:7, 
                           labels = label_wik, ordered = TRUE),
         yearmonthf = factor(x = yearmonth))
][, ':='(monthweek = 1 + week - min(week)), by = .(monthf)] # 分组聚合
```

```{r}
ggplot(dat19, aes(weekdayf, monthweek, fill = ValueCol)) + 
  geom_tile(color = "white") + 
  geom_text(aes(label = day), size = 3) + 
  scale_fill_gradientn(colours = rev(brewer.pal(11, "Spectral"))) + 
  facet_wrap(~monthf, nrow = 3) + 
  scale_y_reverse(name = "Week of the month") + 
  xlab("Day") +
  theme(strip.text = element_text(size = 11, face = "plain", color = "black"),
        panel.grid = element_blank())
```











